### ISSUE TITLE
How do you plan to differ from Redsmin & RDM ?

### ISSUE THREAD

**Issue by FGRibreau** [mauersu/redis-admin#1]
Hello @mauersu!

How do you plan to differ from [Redsmin](https://redsmin.com) or RDM?

**Comment by mauersu** [comment]
Hello 
[Redsmin](https://redsmin.com)  is greatest i had see , i like it. 
you see, i have little user now,my plan is fulfil my users requirement and release redis-admin.0.0.1.release.

**Comment by FGRibreau** [comment]
Ok :)

**Comment by mauersu** [comment]
: )
