### ISSUE TITLE
有没有打算用spring-boot做

### ISSUE THREAD

**Issue by kgdngitfk** [mauersu/redis-admin#11]
这样的B/S端需要放在容器中或者mvn jetty:run 或者mvn tomcat7:run才行，对于使用者来说多了一步安装web服务器或者maven显然使用上不是很方便，spring-boot可以将容器嵌入到web应用中，这样就只需要
java -jar xx.war就可以启动然后在浏览器中访问了

**Comment by mauersu** [comment]
@kgdngitfk 我研究下spring-boot，好久不关注web框架东西了

**Comment by mauersu** [comment]
@kgdngitfk https://github.com/mauersu/redis-admin/tree/dev_springboot_20190512
