### ISSUE TITLE
Tomcat8.5/9下面war包运行报错，而且页面也打不开？idea下面是可以的。

### ISSUE THREAD

**Issue by zhaojihuionline** [mauersu/redis-admin#15]
各种尝试不行……？

**Comment by LarimarTyl** [comment]
已经解决了，我用的SpringBoot的那个分支，打包到tomcat下运行，报了一个什么ContextLoaderListener相关的错误，是因为SpringBoot打包到tomcat运行启动类需要继承SpringBootServletInitializer然后重写configure方法，然后这个过程中已经初始化了一次ContextLoaderListener但是在web.xml中也有一个ContextLoaderListener的配置，把web.xml中的ContextLoaderListener相关配置注释了就可以了。
