### ISSUE TITLE
modify pom target so that application can be ran as `mvn tomcat:run`

### ISSUE THREAD

**Issue by gabhi** [mauersu/redis-admin#3]
current version requires copying jar from target folder and put it in external tomcat. this could be replaced by adding tomcat maven plugin and run the app as `mvn tomcat:run` or `mvn jetty:run`

**Comment by mauersu** [comment]
that's a good idea. 
I'm glad you can pull a request for it, thanks.

**Comment by gabhi** [comment]
thanks. I tried fixing but somehow your template was not getting recognized when using tomcat/jetty plugin.

**Comment by mauersu** [comment]
I know, can you pull request I look at what add. then I will try to make it run.

**Comment by mauersu** [comment]
I'm sorry.i forget I cannot test it, i having Chinese New Year holiday and my home-windows-computer donot have redis. I will be back after 10day : (

**Comment by gabhi** [comment]
ohh ok. No worries. Happy New year!!

**Comment by mauersu** [comment]
@gabhi  I am  back now, let's finish it.
